In [1]:
import numpy as np

# -----------------------------
# Random Seed
# -----------------------------
np.random.seed(25)

# -----------------------------
# Sample Token IDs
# (Output from BPE)
# -----------------------------
tokens = np.array([4,8,15,16,23,42,10,6,9,14,18,27,31,12,7])

sequence_length = 4

X = []
Y = []

# -----------------------------
# Create Input-Target Pairs
# -----------------------------
for i in range(len(tokens)-sequence_length):
    X.append(tokens[i:i+sequence_length])
    Y.append(tokens[i+sequence_length])

X = np.array(X)
Y = np.array(Y)

print("Input Sequences")
print(X)

print("\nTarget Tokens")
print(Y)

# -----------------------------
# Embedding Layer
# -----------------------------
vocab_size = 50
embedding_dim = 8

embedding = np.random.randn(vocab_size, embedding_dim)

embedded_input = embedding[X]

print("\nEmbedded Shape :", embedded_input.shape)

# -----------------------------
# Positional Encoding
# -----------------------------
position = np.arange(sequence_length)

pos_encoding = np.random.randn(sequence_length, embedding_dim)

embedded_input = embedded_input + pos_encoding

print("\nPositional Encoding Added")

# -----------------------------
# Causal Mask
# -----------------------------
mask = np.triu(np.ones((sequence_length, sequence_length)), k=1)

print("\nCausal Mask")
print(mask)

# -----------------------------
# Self Attention
# -----------------------------
Q = embedded_input
K = embedded_input
V = embedded_input

scores = np.matmul(Q, K.transpose(0,2,1))

scores = scores / np.sqrt(embedding_dim)

scores = np.where(mask==1, -1e9, scores)

attention = np.exp(scores)
attention = attention / attention.sum(axis=-1, keepdims=True)

context = np.matmul(attention, V)

print("\nContext Shape :", context.shape)

# -----------------------------
# Linear Layer
# -----------------------------
W = np.random.randn(embedding_dim, vocab_size)

logits = np.matmul(context[:, -1, :], W)

print("\nLogits Shape :", logits.shape)

# -----------------------------
# Softmax
# -----------------------------
exp_logits = np.exp(logits - np.max(logits, axis=1, keepdims=True))

probabilities = exp_logits / exp_logits.sum(axis=1, keepdims=True)

print("\nPrediction Probabilities")
print(probabilities)

# -----------------------------
# Predicted Token
# -----------------------------
predicted_tokens = np.argmax(probabilities, axis=1)

print("\nPredicted Next Tokens")
print(predicted_tokens)

# -----------------------------
# Cross Entropy Loss
# -----------------------------
loss = -np.mean(np.log(probabilities[np.arange(len(Y)), Y] + 1e-9))

print("\nLoss :", loss)

# -----------------------------
# Backpropagation
# -----------------------------
print("\nBackpropagation Step (Concept Demonstration)")

# -----------------------------
# Text Generation
# -----------------------------
print("\nGenerated Next Token IDs")

current = list(tokens[:sequence_length])

for i in range(5):

    emb = embedding[np.array(current[-sequence_length:])]
    emb = emb + pos_encoding

    q = emb
    k = emb
    v = emb

    score = np.matmul(q, k.T) / np.sqrt(embedding_dim)

    score = np.where(mask==1, -1e9, score)

    att = np.exp(score)
    att = att / att.sum(axis=-1, keepdims=True)

    ctx = np.matmul(att, v)

    logit = np.matmul(ctx[-1], W)

    prob = np.exp(logit - np.max(logit))
    prob = prob / prob.sum()

    next_token = np.argmax(prob)

    current.append(next_token)

print(current)

print("\nProject Completed Successfully!")

Input Sequences
[[ 4  8 15 16]
 [ 8 15 16 23]
 [15 16 23 42]
 [16 23 42 10]
 [23 42 10  6]
 [42 10  6  9]
 [10  6  9 14]
 [ 6  9 14 18]
 [ 9 14 18 27]
 [14 18 27 31]
 [18 27 31 12]]

Target Tokens
[23 42 10  6  9 14 18 27 31 12  7]

Embedded Shape : (11, 4, 8)

Positional Encoding Added

Causal Mask
[[0. 1. 1. 1.]
 [0. 0. 1. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]

Context Shape : (11, 4, 8)

Logits Shape : (11, 50)

Prediction Probabilities
[[3.00330759e-06 4.24440176e-06 4.38065801e-07 1.31216613e-02
  1.02409456e-03 8.38656914e-07 1.02697680e-07 1.37201258e-05
  1.09486580e-03 2.11476664e-06 5.99553668e-05 8.77996503e-03
  1.50935997e-02 8.24627178e-05 3.20259592e-07 4.46589357e-05
  5.52583953e-06 8.04178195e-05 7.43740650e-06 1.66180728e-03
  1.90056692e-06 2.51097596e-05 1.01890786e-03 8.36979408e-03
  1.30351009e-03 2.80195509e-04 2.10167818e-05 4.79218264e-01
  4.71552107e-04 1.82497207e-06 1.05050005e-04 3.40440634e-03
  2.63008179e-06 6.28183378e-04 2.97187809e-07 4.55494953e-04
 